version: '3.8'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db
    ports:
      - '4000:4000'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8080:3000'

volumes:
  db:
    driver: local

